package service;

import dao.HabitDAO;
import model.Habit;
import model.Habit.Priority;

import java.time.LocalDate;
import java.util.List;

public class HabitService {

    private final HabitDAO habitDAO = new HabitDAO();

    public Habit createHabit(int userId, String name, String description, LocalDate dueDate, Priority priority) {
        // id is generated by DB, so use 0 as placeholder
        Habit h = new Habit(0, name, description, dueDate, priority);
        habitDAO.insert(h, userId);
        return h;
    }

    public Habit createHabitForGoal(int userId, Integer goalId, String name, String description, LocalDate dueDate, Priority priority) {
        Habit h = new Habit(0, name, description, dueDate, priority);
        h.setGoalId(goalId);
        habitDAO.insert(h, userId);
        return h;
    }

    public List<Habit> listHabits(int userId) {
        return habitDAO.findAll(userId);
    }

    public boolean markComplete(int id) {
        return habitDAO.setCompleted(id, true);
    }

    public boolean markIncomplete(int id) {
        return habitDAO.setCompleted(id, false);
    }

    // --- NEW METHODS ---
    public Habit findHabitById(int id) {
        return habitDAO.findById(id);
    }

    public boolean updateHabit(int id, String name, String description, LocalDate dueDate, Priority priority, Integer goalId) {
        return habitDAO.update(id, name, description == null ? "" : description, dueDate, priority, goalId);
    }

    public boolean deleteHabit(int id) {
        return habitDAO.deleteById(id);
    }
}
